all:
	gcc -c hw0401.c
	gcc -c myfunc.c
	gcc hw0401.o myfunc.o -std=c11 -lm -o hw0401
	gcc -c hw0402.c
	gcc -c mine.c
	gcc hw0402.o mine.o -o hw0402
	gcc hw0403.c -o hw0403
	gcc hw0404.c -o hw0404
	gcc hw0405.c -lm -o hw0405
	
