all:
	gcc -c hw0301.c
	gcc -lm -c myfunc.c
	gcc hw0301.o myfunc.o -o hw0301
	gcc -c hw0302.c
	gcc -c mystddev.c
	gcc hw0302.o mystddev.o -o hw0302
	gcc -c -lm hw0303.c
	gcc -c resistance.c
	gcc hw0303.o resistance.o -o hw0303
	gcc -c hw0304-1.c
	gcc -c hanoi.c
	gcc hw0304-1.o hanoi.o -o hw0304-1
	gcc hw0304-2.c -lm -o hw0304-2
	gcc -c hw0305.c
	gcc -c logic.c
	gcc -c smallten.c
	gcc logic.o smallten.o hw0305.o -lm -o hw0305
